---
title: "EDS 221 Day 7 Interactive Session"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(palmerpenguins)
library(lubridate)

```


```{r}
palmerpenguins <- palmerpenguins::penguins
refresher_1 <- palmerpenguins |>
  filter(island == c("Biscoe","Dream")) |>
  select(-year, -sex) |>
  mutate(body_mass_kg = body_mass_g / 1000) |>
  rename(location = island)

```


```{r}
refresher_2 <- palmerpenguins |>
  filter(species == "Adelie") |>
  filter(is.na(flipper_length_mm)) |>
  group_by(sex) |>
  summarize(penguin_mean = mean(flipper_length_mm, na.rm = TRUE), penguin_stdev = sd(flipper_length_mm, na.rm = TRUE), penguin_sum = n()) 


```



```{r}
animals <- tibble::tribble(
  ~location,   ~species,  ~maturity,
   "lagoon",   "bobcat",    "adult",
    "bluff",   "coyote", "juvenile",
    "creek",      "fox",    "adult",
     "oaks", "squirrel", "juvenile",
    "bluff",   "bobcat",    "adult"
  )


sites <- tibble::tribble(
  ~location,      ~full_site_name, ~jurisdiction,
    "beach",       "Goleta Beach",     "SB City",
   "lagoon",        "UCSB Lagoon",        "UCSB",
    "bluff",       "Ellwood Mesa",     "SB City",
     "oaks", "Fremont Campground",        "USFS"
  )

```


#mutating join
```{r}
example_full_join <-
full_join(animals, sites)

example_left_join <-
  left_join(animals, sites)

example_right_join <-
  right_join(animals, sites)

example_inner_join <-
  inner_join(animals, sites)

```

#filtering joins
```{r}

example_semi_join <-
  semi_join(animals, sites, by = "location")

example_anti_join <-
  anti_join(animals, sites)

```



```{r}

sites_test <- sites |>
  rename(place = location)

test_join <- full_join(animals, sites_test, by = c("location" = "place"))


```



```{r}
library(tidyverse)
library(lubridate)

```



```{r}
my_date <- "03-05-1998"
lubridate::mdy(my_date)

my_date <- "11/7/2003"
lubridate::mdy(my_date)

my_date <- "08-Jun-1991"
dmy(my_date)

my_date <- "19860518"
ymd(my_date)


time <- "2020-08-12 11:18"
time <- lubridate::ymd_hm(time)
class(time)


with_tz(time, "America/Los_Angeles")
with_tz(time, "Australia/Sydney")

```


```{r}

my_time <- lubridate::ymd_hms(time)

week(my_time)

hour(my_time)

day(my_time)
minute(my_time)
year(my_time)
month(my_time)


```


```{r}

# Get your system time
comp_time <- Sys.time()
# Convert comp_time to Europe/Belgrade time: 
with_tz(comp_time, "Europe/Belgrade")



```


```{r}
urchin_counts <- tribble(
  ~date, ~species, ~size_mm,
  "10/3/2020", "purple", 55,
  "10/4/2020", "red", 48,
  "11/17/2020", "red", 67
)

urchin_counts <- urchin_counts |>
  mutate(date = lubridate::mdy(date)) |>
  mutate(year = year(date),
         month = month(date),
         day = day(date)) 

urchin_counts |>
  group_by(year) |>
  summarize(total = n())


```

```{r}

day_1 <- lubridate::ymd("2020-01-06")
day_2 <- ymd("2020-05-18")
day_3 <- ymd("2024-08-19")

time_interval <- interval(day_1, day_2)
time_length(time_interval, "day")
time_length(interval(day_2, day_3), "year")

day_now <- lubridate::ymd("2024-08-20")
day_born <- ymd("1999-11-19")

time_length(interval(day_now, day_born), "day")
```




```{r}

my_string <- "Teddy loves eating salmon and socks"
my_string |>
  str_detect("lover")

my_string <- c("burrito", "fish taco", "taco salad")

my_string |>
  str_detect("fish")

```



```{r}
 
skywalkers <- starwars |>
  filter(str_detect(name, "Skywalker"))


firewalkers <- starwars |>
  mutate(name = str_replace(name, 
                            pattern = "Sky", 
                            replacement = "Fire"))

```


```{r}
feedback <- c(" I ate   some nachos", "Wednesday morning   ")

str_squish(feedback)

str_trim(feedback)

str_to_lower(feedback)
str_to_upper(feedback)
str_to_title(feedback)

str_count(feedback, pattern = "nachos")

```

